# Generated by Django 3.2.4 on 2022-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0002_auto_20220716_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='subtopic_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
