# Generated by Django 3.2.4 on 2022-07-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0004_auto_20220720_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='level',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='topic_id',
        ),
        migrations.DeleteModel(
            name='MatchTheColumns',
        ),
        migrations.DeleteModel(
            name='subtopic',
        ),
        migrations.DeleteModel(
            name='topic',
        ),
    ]
