# Generated by Django 3.2.4 on 2022-07-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0005_auto_20220721_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_bank',
            options={'ordering': ('-created',), 'verbose_name': 'Question Bank', 'verbose_name_plural': 'Question Banks'},
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_exam.user'),
        ),
    ]
