# Generated by Django 3.2.4 on 2022-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0008_alter_course_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-created',), 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(default='', max_length=100),
        ),
    ]
