# Generated by Django 3.2.4 on 2022-07-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0009_auto_20220721_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTheColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null='True')),
                ('answer', models.TextField(blank=True, null='True')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank')),
            ],
        ),
    ]
